### PR TITLE
Move toll booth examples to c04extra package

### PR DESCRIPTION
**Pull request by Boiarshinov**

### CODE REVIEW

**Comment by joshfischer1108** [comment]
@nwangtw can you review this when you have some time?

**Comment by nwangtw** [comment]
What are the main changesin this PR? And what is the goal for renaming the package?

**Comment by Boiarshinov** [comment]
Hi @nwangtw! I wrote about the reasons of this PR in related issue: https://github.com/nwangtw/GrokkingStreamingSystems/issues/12

tl;dr: There was nothing about Toll Booth in chapter 4 in the book. So the code with Toll Booth jobs is related to chapter 4 indirectly

**Comment by nwangtw** [comment]
> Hi @nwangtw! I wrote about the reasons of this PR in related issue: #12
> 
> tl;dr: There was nothing about Toll Booth in chapter 4 in the book. So the code with Toll Booth jobs is related to chapter 4 indirectly

I see. Thanks for pointing it out.

Chapter 4 is about split, fork, etc., but there is no story in this chapter, so we are using the code from chapter 3 as the start point to demo how split, fork, etc. work in the engine and code. Otherwise, the code for chapter 4 will be an updated engine only which won't be helpful.

That being said, your point is valid. I have a proposal: how about we keep the engine/api/etc in the `ch04` package and move the code for the jobs to the new `ch04extra` package? It is a little aggressive to me to move everything to the new package and the package name is inconsistent with the other chapters. So I am wondering if there is a better way to organize the files.

Again, thanks for your help!

**Comment by Boiarshinov** [comment]
I've refactored code with your recommendations (all commits are squashed). Could you check please?
Also I've add package-info file with some examples description

**Review by nwangtw — APPROVED** [review]
Great! Thanks!

**Pull request merged**
